name: applied-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - joblib
  - jupyter
  - ipykernel
  - pytorch
  - cpuonly          # remove this line and add pytorch-cuda=12.1 for GPU
  - pip
  - pip:
    - wandb
